version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1
  python: circleci/python@1.2.0
  ftest: jimicircleci/fcheck@dev:<<pipeline.git.revision>>

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create jobs to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  my-job:
    executor: python/default
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - run: pip install black
      - ftest/format:
          path: sample_files

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
      - my-job:
          filters: *filters
      - orb-tools/publish:
          orb_name: jimicircleci/fcheck
          vcs_type: << pipeline.project.type >>
          requires: [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          context: orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: fcheck
          requires: [orb-tools/publish]
          filters: *filters
